### ISSUE TITLE
Redirect from "/" to Home

### ISSUE THREAD

**Issue by tpokora** [tpokora/emmy#41]

**Comment by Jataki** [comment]
Hi. Can I take this?

**Comment by tpokora** [comment]
@Jataki Sure, check: https://vaadin.com/docs/v10/flow/routing/tutorial-routing-exception-handling.html maybe it will help

**Comment by Jataki** [comment]
Having an issue with my computer with no solution date. I'm sorry, but I'll have to leave this issue for others to have the opportunity to contribute. Thanks anyway and I'm so sorry!

**Comment by tpokora** [comment]
@Jataki, no worries :)

**Comment by tpokora** [comment]
Will remove Vaddin framework. Issue invalid
